"""Port exposing the single-fact use case to batch and migration flows."""
from typing import Any, Optional, Protocol, Tuple


class AddFact(Protocol):
    def validate_fact(self, fact, db_path=None) -> Tuple[list, list]: ...
    def build_entry(self, fact, visibility=None) -> dict: ...
    def resolve_privacy(self, fact, data_path, db_path) -> Any: ...
    def canonicalize_subject(self, fact, data_path) -> Tuple[list, Optional[str]]: ...
    def append_fact(self, fact, data_path=None, db_path=None) -> Any: ...
