"""Port for reading and editing persisted entity data."""
from typing import Any, Optional, Protocol
from private_git_port import PrivateGit


class EntityFiles(Protocol):
    ENTITY_TYPES: tuple
    def read_file(self, path=None) -> Optional[list]: ...
    def find(self, entities, ref) -> Optional[dict]: ...
    def edit_file(self, edit, what, message, allow_dirty=False, dry_run=False, path=None, *, git: PrivateGit) -> Any: ...
    def add_entity(self, entities, name, entity_type, aliases=(), private=False, external_id=None, notes=None) -> Any: ...
    def add_alias(self, entities, ref, alias) -> Any: ...
    def set_private(self, entities, ref, private) -> Any: ...
