"""Read port for entity links and subject hierarchy query results."""
from typing import Any, Protocol


class EntityQueries(Protocol):
    def entity_link_counts(self) -> dict: ...
    def known_subjects(self) -> dict: ...
    def subject_rows(self, db: Any = None) -> list: ...
