"""Port for the persisted fact-entry file and its validation lookups."""
from typing import Optional, Protocol, Tuple


class FactsFile(Protocol):
    """The locked JSON array of new facts and its source/subject lookups."""

    def read_array(self, path) -> list: ...
    def append_record(self, path, record) -> int: ...
    def append_records(self, path, records, reject=None) -> Tuple[int, list]: ...
    def citekey_problem(self, db_path, citekey) -> Tuple[Optional[str], Optional[str]]: ...
    def subject_tree(self, db_path) -> Tuple[dict, Optional[set]]: ...
    def file_subjects(self, data_path) -> set: ...
    def data_dir_of(self, data_path) -> str: ...
    def file_sha256(self, path) -> Optional[str]: ...
    def canonical_subject(self, data_path, subject) -> Tuple[str, list, Optional[str]]: ...
