"""Port for discovering and reading source memory files."""
from typing import Any, ContextManager, Dict, Protocol


class MemoryFiles(Protocol):
    def root_exists(self, root) -> bool: ...
    def absolute_root(self, root) -> str: ...
    def discover(self, root) -> tuple: ...
    def read_memory_file(self, path, project, filename) -> Any: ...
    def existing_entries(self, data_dir) -> Dict[str, str]: ...
    def run_lock(self, data_path) -> ContextManager: ...
    def data_dir_of(self, data_path) -> str: ...
