"""Port for reading and editing the persisted privacy rules."""
from typing import Any, Protocol


class Rules(Protocol):
    def load_rules(self, path=None) -> Any: ...
    def save_rules(self, rules, path) -> None: ...
    def rules_path(self, data_dir=None) -> str: ...
    def data_dir_of(self, path) -> str: ...
    def existing_ancestor(self, directory) -> str: ...
    def make_dirs(self, directory) -> None: ...
