"""Port for persisted entries and their append-only revision log."""
from typing import Any, List, Optional, Protocol, Tuple


class Revisions(Protocol):
    def default_data_dir(self) -> str: ...
    def load_entries(self, data_dir=None) -> List[dict]: ...
    def read_log(self, path, base=None) -> List[Tuple[int, dict]]: ...
    def append_revision(self, source_key, changes, reason, via, session_id=None, data_dir=None,
                        revisions_path=None, expect=None) -> Any: ...
