"""Read port for the pending review queue and current fact states."""
from typing import Dict, List, Optional, Protocol, Tuple


class ReviewReads(Protocol):
    def default_data_dir(self) -> str: ...
    def db_exists(self, db_path) -> bool: ...
    def list_pending(self, db) -> List[dict]: ...
    def current_states(self, data_dir=None) -> Dict[str, dict]: ...
    def subject_parents(self, db) -> Dict[str, Optional[str]]: ...
    def source_key_for_id(self, db, fact_id) -> Tuple[bool, Optional[str]]: ...
