"""Port exposing review operations to lifecycle use cases."""
from typing import Any, Dict, Optional, Protocol, Tuple


class Reviews(Protocol):
    def current_states(self, data_dir=None) -> Dict[str, dict]: ...
    def resolve_ref(self, ref, states, db) -> Tuple[Optional[str], Optional[str]]: ...
    def rules_with_db_context(self, data_dir, db) -> Any: ...
    def status_word(self, status) -> str: ...
