"""Port for reading and editing the persisted subject hierarchy."""
from typing import Any, Protocol
from private_git_port import PrivateGit


class SubjectFiles(Protocol):
    def edit_file(self, edit, what, message, allow_dirty=False, dry_run=False, path=None, *, git: PrivateGit) -> Any: ...
    def add_alias(self, entries, name, alias, known=None, domain=None) -> Any: ...
    def describe(self, entries, name, text, known=None, domain=None) -> Any: ...
    def deprecate(self, entries, name, replaced_by=None, known=None, domain=None) -> Any: ...
